-- =============================================
-- Migration: 007_create_migration_history
-- Description: Create EF6 __MigrationHistory table
-- Target: Old-structure database (run in SSMS)
-- =============================================

PRINT 'Starting migration 007_create_migration_history...'
PRINT 'Target: Create EF6 migration tracking table'
PRINT ''

-- =============================================
-- __MIGRATIONHISTORY TABLE
-- =============================================
PRINT 'Processing __MigrationHistory table...'

IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE name = '__MigrationHistory' AND type = 'U')
BEGIN
    CREATE TABLE [dbo].[__MigrationHistory](
        [MigrationId] [nvarchar](150) NOT NULL,
        [ContextKey] [nvarchar](300) NOT NULL,
        [Model] [varbinary](max) NOT NULL,
        [ProductVersion] [nvarchar](32) NOT NULL,
        CONSTRAINT [PK_dbo.__MigrationHistory] PRIMARY KEY CLUSTERED
        (
            [MigrationId] ASC,
            [ContextKey] ASC
        ) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
    ) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

    PRINT '  Created table: __MigrationHistory'
END
ELSE
    PRINT '  Table already exists: __MigrationHistory'
GO

-- =============================================
-- INSERT INITIAL MIGRATION RECORD
-- =============================================
PRINT ''
PRINT 'Inserting initial migration record...'

-- Note: The Model column should contain the EDMX model in compressed format
-- This is typically generated by Entity Framework during code-first migrations
-- For manual migrations, we insert a placeholder that EF6 can recognize

DECLARE @contextKey NVARCHAR(300) = 'ePacific.Data.Migrations.Configuration'
DECLARE @migrationId NVARCHAR(150) = '000000000000000_InitialCreate'
DECLARE @productVersion NVARCHAR(32) = '6.4.4'

IF NOT EXISTS (
    SELECT 1 FROM [dbo].[__MigrationHistory]
    WHERE MigrationId = @migrationId AND ContextKey = @contextKey
)
BEGIN
    -- Insert a minimal migration record
    -- The Model is a minimal placeholder - in production, this should be the actual EF model
    INSERT INTO [dbo].[__MigrationHistory] ([MigrationId], [ContextKey], [Model], [ProductVersion])
    VALUES (
        @migrationId,
        @contextKey,
        0x1F8B0800000000000400ECBD07601C499625262F6DCA7B7F4AF54AD7E074A10880601324D8904010ECC188CDE692EC1D69472329AB2A81CA6556655D661640CCED9DBCF7DE7BEFBDF7DE7BEFBDF7BA3B9D4E27F7DFFF3F5C6664016CF6CE4ADAC99E2180AAC81F3F7E7C1F3F227EF147BF5A399DE5E5F49BEF5C4A7BDBF060FAECDDDBDDD7C3D8F8F9F9F1F7F7E7E3F3F1F1F3E7F3F7E3B7C7C7C3CFEFEE7F3F3E17E7EFCFCFCFCF0F0F0F1E0E0E0E0E1C1C1C1C3C3C3C7C7C78F8F8F8F9F9F9F3F3F3F7F7F7F7FFFFFFFFFFF,
        @productVersion
    )
    PRINT '  Inserted initial migration record'
END
ELSE
    PRINT '  Initial migration record already exists'
GO

PRINT ''
PRINT '============================================='
PRINT 'Migration 007_create_migration_history completed!'
PRINT ''
PRINT 'The database is now configured for Entity Framework 6.'
PRINT 'EF6 will use the __MigrationHistory table to track'
PRINT 'future migrations applied through code-first migrations.'
PRINT '============================================='
GO

-- =============================================
-- FINAL SUMMARY
-- =============================================
PRINT ''
PRINT '================================================================================'
PRINT '                    DATABASE MIGRATION COMPLETE'
PRINT '================================================================================'
PRINT ''
PRINT 'The following migrations have been applied:'
PRINT '  001_add_new_columns.sql        - Added new columns to existing tables'
PRINT '  002_create_new_tables.sql      - Created new tables for EF6 schema'
PRINT '  003_rename_primary_keys.sql    - Renamed PKs to EF6 convention (PK_dbo.TableName)'
PRINT '  004_update_views.sql           - Updated views to match new schema'
PRINT '  005_update_stored_procedures.sql - Updated stored procedures'
PRINT '  006_add_foreign_keys.sql       - Added new foreign key constraints'
PRINT '  007_create_migration_history.sql - Created EF6 migration tracking'
PRINT ''
PRINT 'POST-MIGRATION ACTIONS REQUIRED:'
PRINT '  1. Verify all stored procedures were recreated correctly'
PRINT '  2. Run validation queries to confirm data integrity'
PRINT '  3. Test application connectivity'
PRINT '  4. Update database compatibility level if needed:'
PRINT '     ALTER DATABASE [YourDatabase] SET COMPATIBILITY_LEVEL = 150'
PRINT ''
PRINT '================================================================================'
GO
